console.log('date object');
// let today=Date();
// console.log(today);
// // let otherdate=new Date('8-9-2023 04:43:35');
// // let otherdate=new Date('april 10 2003 10:33:60');
// let otherdate=new Date('09/14/2000 07:45:22');
// console.log(otherdate);
// let a;
// // a=otherdate.getDate();
// // a=otherdate.getDay();
// // a=otherdate.getMonth();
// // a=otherdate.getFullYear();
// // a=otherdate.getTime();
// // a=otherdate.getHours();
// // a=otherdate.getMinutes();
// // a=otherdate.getSeconds();
// // a=otherdate.getMilliseconds();
// // console.log(a);
// otherdate.setDate(23);
// otherdate.setMonth(12);
// otherdate.setFullYear(3000);
// otherdate.setMinutes(12);
// otherdate.setSeconds(34);
// otherdate.setHours(23);
// otherdate.setTime(20)
// console.log(otherdate);
let today=new Date();
// today.setHours(10);
alert(today);
